/// Static configuration for the Smart Fridge app.
///
/// Nothing here is a secret. Real Firebase credentials live in
/// `firebase_options.dart` (generated by `flutterfire configure`).
class AppConfig {
  /// The device this app instance monitors. Must match the firmware.
  static const String deviceId = 'fridge_01';

  /// Realtime Database root for this device.
  static String get deviceRoot => 'devices/$deviceId';

  /// Product categories supported by the risk model.
  static const List<String> categories = <String>[
    'Fruit',
    'Vegetable',
    'Dairy',
    'Egg',
    'Packaged Food',
  ];

  /// Box dimensions, shown on the Settings screen.
  static const String boxDimensions = '47 x 72.5 x 36.2 cm';
}
