/// Static configuration for the Smart Fridge app.
///
/// Nothing here is a secret. Real Firebase credentials live in
/// `firebase_options.dart` (generated by `flutterfire configure`).
class AppConfig {
  /// The device this app instance monitors. Must match the ESP32 firmware.
  static const String deviceId = 'fridge_01';

  /// Realtime Database root for this device.
  static String get deviceRoot => 'devices/$deviceId';
}
